package SimpArc;
import java.awt.*;

import Lab5.client;
import Lab5.server;
import simView.*;

public class handshake extends ViewableDigraph
{

	public handshake()
	{
		super("gpt");
    	
		ViewableAtomic g = new client("g", 10);	
		ViewableAtomic p = new server("p", 10);	
    	
		add(g);	
		add(p);
		addCoupling(g, "out", p, "in");
		addCoupling(p, "out", g, "in");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("g")).setPreferredLocation(new Point(383, 132));
        ((ViewableComponent)withName("p")).setPreferredLocation(new Point(393, 360));
    }
}
