package Lab6;
import java.awt.*;
import simView.*;

public class routing_model extends ViewableDigraph
{

	public routing_model()
	{
		super("routing_model");
    	
		ViewableAtomic g = new sender("sender", 10); // ?–´?–¤ ëª¨ë¸?„ ê°?? ¸?‹¤ ?“¸ ê±´ì? ?“±
		ViewableAtomic r = new router("router", 10); 
    	
		add(g); // ?‹œë®¬ë ˆ?´?„°?— ëª¨ë¸ ?“±ë¡?
		add(r);
		
		for(int i = 1; i <= 5; i++) {
			ViewableAtomic p = new receiver("receiver #" + i, 10);
			add(p);
			addCoupling(r, "out" + i, p, "in");
		}
  
		// addCoupling(A ëª¨ë¸?¼ë¦?, A?˜ ?•„?›ƒ?’‹ ?¬?Š¸ ?´ë¦?, B?˜ ëª¨ë¸ ?´ë¦?, B?˜ ?¸ ?¬?Š¸ ?´ë¦?) 
		
		// 
		addCoupling(g, "out", r, "in");
		addCoupling(r, "out", g, "in");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("receiver #2")).setPreferredLocation(new Point(688, 189));
        ((ViewableComponent)withName("router")).setPreferredLocation(new Point(247, 325));
        ((ViewableComponent)withName("receiver #3")).setPreferredLocation(new Point(689, 287));
        ((ViewableComponent)withName("receiver #5")).setPreferredLocation(new Point(688, 429));
        ((ViewableComponent)withName("receiver #1")).setPreferredLocation(new Point(689, 95));
        ((ViewableComponent)withName("receiver #4")).setPreferredLocation(new Point(685, 369));
        ((ViewableComponent)withName("sender")).setPreferredLocation(new Point(233, 74));
    }
}
